class ClassMenuPresets {
    public static var acrobat = ["stealth",
        "acrobatics",
        "blade",
        "block",
        "marksman",
        "security",
        "sneak",
        "speechcraft",
        "agility",
        "endurance"];
    public static var agent = ["stealth",
        "acrobatics",
        "illusion",
        "marksman",
        "mercantile",
        "security",
        "sneak",
        "speechcraft",
        "personality",
        "agility"];
    public static var archer = ["combat",
        "armorer",
        "blade",
        "blunt",
        "hand_to_hand",
        "light_armor",
        "marksman",
        "sneak",
        "agility",
        "strength"];
    public static var assassin = ["stealth",
        "acrobatics",
        "alchemy",
        "blade",
        "marksman",
        "light_armor",
        "security",
        "sneak",
        "speed",
        "intelligence"];
    public static var barbarian = ["combat",
        "armorer",
        "athletics",
        "blade",
        "block",
        "blunt",
        "hand_to_hand",
        "light_armor",
        "strength",
        "speed"]
    public static var bard = ["stealth",
        "alchemy",
        "blade",
        "block",
        "illusion",
        "light_armor",
        "mercantile",
        "speechcraft",
        "personality",
        "intelligence"];
    public static var battlemage = ["magic",
        "alchemy",
        "alteration",
        "blade",
        "blunt",
        "conjuration",
        "destruction",
        "mysticism",
        "intelligence",
        "strength"];
    public static var crusader = ["combat",
        "athletics",
        "blade",
        "blunt",
        "destruction",
        "hand_to_hand",
        "heavy_armor",
        "restoration",
        "agility",
        "strength"];
    public static var healer = ["magic",
        "alchemy",
        "alteration",
        "destruction",
        "illusion",
        "mercantile",
        "restoration",
        "speechcraft",
        "willpower",
        "personality"];
    public static var knight = ["combat",
        "blade",
        "block",
        "blunt",
        "hand_to_hand",
        "heavy_armor",
        "illusion",
        "speechcraft",
        "strength",
        "personality"];
    public static var mage = ["magic",
        "alchemy",
        "alteration",
        "conjuration",
        "destruction",
        "illusion",
        "mysticism",
        "restoration",
        "intelligence",
        "willpower"];
    public static var monk = ["stealth",
        "acrobatics",
        "alteration",
        "athletics",
        "hand_to_hand",
        "marksman",
        "security",
        "sneak",
        "agility",
        "willpower"];
    public static var nightblade = ["magic",
        "acrobatics",
        "alteration",
        "athletics",
        "blade",
        "destruction",
        "light_armor",
        "restoration",
        "willpower",
        "speed"];
    public static var pilgrim = ["stealth",
        "armorer",
        "block",
        "blunt",
        "light_armor",
        "mercantile",
        "security",
        "speechcraft",
        "personality",
        "endurance"];
    public static var rogue = ["combat",
        "alchemy",
        "athletics",
        "blade",
        "block",
        "illusion",
        "light_armor",
        "mercantile",
        "speed",
        "personality"];
    public static var scout = ["combat",
        "acrobatics",
        "alchemy",
        "armorer",
        "athletics",
        "blade",
        "block",
        "light_armor",
        "speed",
        "endurance"]
    public static var sorcerer = ["magic",
        "alchemy",
        "alteration",
        "conjuration",
        "destruction",
        "heavy_armor",
        "mysticism",
        "restoration",
        "intelligence",
        "endurance"];
    public static var spellsword = ["magic",
        "alteration",
        "blade",
        "block",
        "heavy_armor",
        "destruction",
        "illusion",
        "restoration",
        "willpower",
        "endurance"];
    public static var thief = ["stealth",
        "acrobatics",
        "light_armor",
        "marksman",
        "mercantile",
        "security",
        "sneak",
        "speechcraft",
        "speed",
        "agility"];
    public static var warrior = ["combat",
        "armorer",
        "athletics",
        "blade",
        "block",
        "blunt",
        "hand_to_hand",
        "heavy_armor",
        "strength",
        "endurance"]
    public static var witchhunter = ["magic",
        "alchemy",
        "athletics",
        "conjuration",
        "destruction",
        "marksman",
        "mysticism",
        "security",
        "intelligence",
        "agility"];
}
